[build]
  command = "node build-menu.js"
  publish = "."
  functions = "netlify/functions"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[build.environment]
  NODE_VERSION = "18"
